### ISSUE TITLE
Conversion to vcf

### ISSUE THREAD

**Issue by standard-aaron** [pkalbers/geva#2]
This is not an issue per se, but I'm curious whether you have any suggestions/scripts for converting MS-style output to vcf format (which the documentation states is the only input format, unless I missed something)? 

Thanks,
Aaron

**Comment by hyanwong** [comment]
@35ajstern - we have some code that will convert the VCF output from `msprime` into a format suitable for input into GEVA. We can post it here if you like. If you specifically want `ms` output, then `msprime` now has a `from_ms` converter too.
